/**
 * Daytona sandbox lifecycle for a Temporal dev environment.
 *
 * Each (pattern, language) pair gets its own Daytona snapshot. Workflow code
 * lives in `patterns/<pattern>/<lang>/` and is described by `pattern.json`.
 */

import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { setTimeout as sleep } from "node:timers/promises";

import { Daytona, Image, type Sandbox } from "@daytonaio/sdk";

const TEMPORAL_UI_PORT = 8233;
const APP_DIR = "/opt/app";
const TEMPORAL_BIN = "/usr/local/bin/temporal";

const AUTO_STOP_MINUTES = 15;
const AUTO_DELETE_MINUTES = 30;
const PREVIEW_URL_TTL_SECONDS = 3600;

const PATTERNS_DIR = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "..",
  "patterns",
);

// Per-language toolchain assets shared across patterns: deps file (e.g.
// package.json), tsconfig, warmup stub, etc. Each pattern only owns its
// workflow source; everything common lives here.
const RUNTIME_DIR = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "..",
  "runtime",
);

interface LanguageManifest {
  label: string;
  files: string[];
  worker: string;
  starter: string;
  workerProcessPattern: string;
  diskGib?: number;
  memoryGib?: number;
}

interface PatternManifest {
  name: string;
  languages: Record<string, LanguageManifest>;
}

export type Logger = (msg: string) => void;

// SandboxEvents bundles a regular append-only log channel with a single
// replaceable spinner line. Pass `null` to spinner() to clear it.
export interface SandboxEvents {
  log: (msg: string) => void;
  spinner: (text: string | null) => void;
}

const SPINNER_FRAMES = ["⠋", "⠙", "⠹", "⠸", "⠼", "⠴", "⠦", "⠧", "⠇", "⠏"];

function startSpinner(events: SandboxEvents, label: string): () => void {
  let i = 0;
  events.spinner(`${SPINNER_FRAMES[0]} ${label}`);
  const handle = setInterval(() => {
    i = (i + 1) % SPINNER_FRAMES.length;
    events.spinner(`${SPINNER_FRAMES[i]} ${label}`);
  }, 100);
  return () => {
    clearInterval(handle);
    events.spinner(null);
  };
}

export interface UiInfo {
  sandboxId: string;
  uiUrl: string;
}

export interface LaunchResult extends UiInfo {
  workflowResult: string;
}

export type Language = string;

const TEMPORAL_CLI_INSTALL = [
  "apt-get update",
  "apt-get install -y --no-install-recommends curl ca-certificates",
  'arch=$(uname -m | sed "s/x86_64/amd64/;s/aarch64/arm64/")',
  'curl -fsSL "https://temporal.download/cli/archive/latest?platform=linux&arch=$arch" -o /tmp/t.tgz',
  `tar -xzf /tmp/t.tgz -C ${path.dirname(TEMPORAL_BIN)} temporal`,
  `chmod +x ${TEMPORAL_BIN}`,
  "rm /tmp/t.tgz",
  "rm -rf /var/lib/apt/lists/*",
].join(" && ");

// Per-language Daytona Image factory. Each builds the language runtime,
// installs the Temporal CLI, and bakes the language's deps + warmup files
// from `runtime/<language>/` into the snapshot. The factories don't take
// any pattern-specific input — image fingerprint is stable across patterns,
// so one cached snapshot serves every pattern that shares a language.
const IMAGE_FACTORIES: Record<string, () => Image> = {
  typescript: () =>
    Image.base("node:20-bookworm-slim")
      .runCommands(TEMPORAL_CLI_INSTALL)
      .workdir(APP_DIR)
      .addLocalFile(path.join(RUNTIME_DIR, "typescript", "package.json"), `${APP_DIR}/package.json`)
      .runCommands(`cd ${APP_DIR} && npm install --silent`),
  python: () =>
    Image.base("ghcr.io/astral-sh/uv:python3.12-bookworm-slim")
      .runCommands(TEMPORAL_CLI_INSTALL)
      .workdir(APP_DIR)
      .addLocalFile(path.join(RUNTIME_DIR, "python", "pyproject.toml"), `${APP_DIR}/pyproject.toml`)
      .runCommands(`cd ${APP_DIR} && uv sync`),
  go: () =>
    Image.base("golang:1.22-bookworm")
      .runCommands(TEMPORAL_CLI_INSTALL)
      .workdir(APP_DIR)
      .addLocalFile(path.join(RUNTIME_DIR, "go", "go.mod"), `${APP_DIR}/go.mod`)
      // go.sum is generated by `go mod tidy` and committed alongside go.mod
      // so the image build can verify hashes for every transitive dep without
      // running tidy (which needs the source tree we haven't uploaded yet).
      .addLocalFile(path.join(RUNTIME_DIR, "go", "go.sum"), `${APP_DIR}/go.sum`)
      // Compile a stub against the SDK so its archives land in the build
      // cache; without this, the first runtime `go run` spends ~90s compiling
      // and races the starter timeout. NB: the filename intentionally has no
      // leading underscore — Go's package loader filters `_*.go` files even
      // when listed explicitly on the build command line.
      .addLocalFile(path.join(RUNTIME_DIR, "go", "warmup.go"), `${APP_DIR}/warmup.go`)
      .runCommands(
        `cd ${APP_DIR} && go mod download && go build -o /tmp/warmup warmup.go && rm /tmp/warmup warmup.go`,
      ),
  java: () =>
    Image.base("eclipse-temurin:17-jdk")
      .runCommands(
        [
          "apt-get update",
          "apt-get install -y --no-install-recommends curl ca-certificates maven",
          'arch=$(uname -m | sed "s/x86_64/amd64/;s/aarch64/arm64/")',
          'curl -fsSL "https://temporal.download/cli/archive/latest?platform=linux&arch=$arch" -o /tmp/t.tgz',
          `tar -xzf /tmp/t.tgz -C ${path.dirname(TEMPORAL_BIN)} temporal`,
          `chmod +x ${TEMPORAL_BIN}`,
          "rm /tmp/t.tgz",
          "rm -rf /var/lib/apt/lists/*",
        ].join(" && "),
      )
      .workdir(APP_DIR)
      .addLocalFile(path.join(RUNTIME_DIR, "java", "pom.xml"), `${APP_DIR}/pom.xml`)
      // Compile a stub against the SDK at image-build time. dependency:go-offline
      // pulls plugin + project deps into ~/.m2; mvn compile then exercises the
      // compiler plugin and forces SDK class resolution. After the bake, the
      // stub source and target/ are removed so user uploads start clean.
      .addLocalFile(
        path.join(RUNTIME_DIR, "java", "_warmup", "Warmup.java"),
        `${APP_DIR}/src/main/java/Warmup.java`,
      )
      .runCommands(
        `cd ${APP_DIR} && mvn -q -B dependency:go-offline && mvn -q -B compile && rm -rf target src/main/java/Warmup.java`,
      ),
};

// Some Daytona language hints aren't in the SDK enum; fall back to the
// closest accepted value so create() doesn't reject the request.
const DAYTONA_LANGUAGE_HINT: Record<string, "typescript" | "python"> = {
  typescript: "typescript",
  python: "python",
  go: "typescript",
  java: "typescript",
};

interface ResolvedPattern {
  patternId: string;
  language: string;
  manifest: PatternManifest;
  langManifest: LanguageManifest;
  langDir: string;
}

async function loadManifest(patternId: string): Promise<PatternManifest> {
  const manifestPath = path.join(PATTERNS_DIR, patternId, "pattern.json");
  const raw = await fs.readFile(manifestPath, "utf8");
  return JSON.parse(raw) as PatternManifest;
}

async function resolvePattern(
  patternId: string,
  language: string,
): Promise<ResolvedPattern> {
  const manifest = await loadManifest(patternId);
  const langManifest = manifest.languages[language];
  if (!langManifest) {
    const available = Object.keys(manifest.languages).join(", ");
    throw new Error(
      `Pattern '${patternId}' does not support language '${language}'. Available: ${available}`,
    );
  }
  const langDir = path.join(PATTERNS_DIR, patternId, language);
  return { patternId, language, manifest, langManifest, langDir };
}

export async function listPatterns(): Promise<
  Array<{ id: string; manifest: PatternManifest }>
> {
  const entries = await fs.readdir(PATTERNS_DIR, { withFileTypes: true });
  const out: Array<{ id: string; manifest: PatternManifest }> = [];
  for (const entry of entries) {
    if (!entry.isDirectory()) continue;
    try {
      const manifest = await loadManifest(entry.name);
      out.push({ id: entry.name, manifest });
    } catch {
      /* not a pattern dir */
    }
  }
  return out;
}

export class SandboxManager {
  private readonly daytona: Daytona;

  constructor() {
    const apiKey = process.env.DAYTONA_KEY;
    if (!apiKey) {
      throw new Error("DAYTONA_KEY environment variable is required");
    }
    this.daytona = new Daytona({ apiKey });
  }

  async getEditableFiles(
    patternId: string,
    language: string,
  ): Promise<Record<string, string>> {
    const resolved = await resolvePattern(patternId, language);
    const out: Record<string, string> = {};
    for (const filename of resolved.langManifest.files) {
      out[filename] = await fs.readFile(
        path.join(resolved.langDir, filename),
        "utf8",
      );
    }
    return out;
  }

  async launch(
    patternId: string,
    language: string,
    events: SandboxEvents,
    onUiReady?: (info: UiInfo) => void,
  ): Promise<LaunchResult> {
    const resolved = await resolvePattern(patternId, language);
    const factory = IMAGE_FACTORIES[language];
    if (!factory) {
      throw new Error(`No image factory configured for language '${language}'`);
    }
    const image = factory();

    events.log(
      `Creating sandbox for ${resolved.manifest.name} (${resolved.langManifest.label})...`,
    );
    // FLY_APP_NAME is auto-set on fly.io. When present we're in production
    // and keep the console clean (spinner only). Locally we also stream the
    // raw Daytona snapshot-build chunks so the developer sees what's happening
    // during multi-minute first-time bakes.
    const showImageLogs = !process.env.FLY_APP_NAME;
    const stopSpinner = startSpinner(events, "Provisioning sandbox");
    let sandbox;
    try {
      sandbox = await this.daytona.create(
        {
          image,
          language: DAYTONA_LANGUAGE_HINT[language] ?? "typescript",
          autoStopInterval: AUTO_STOP_MINUTES,
          autoDeleteInterval: AUTO_DELETE_MINUTES,
          resources: {
            disk: resolved.langManifest.diskGib ?? 1,
            memory: resolved.langManifest.memoryGib ?? 2,
          },
        },
        // First-time snapshot bakes can take 10+ minutes for compiled
        // languages (Go: SDK download + warmup compile; Java: dependency
        // download + warmup compile). Subsequent launches hit the cached
        // snapshot and finish well under the default 60s, so this generous
        // ceiling only affects the first build per language.
        {
          timeout: 120,
          ...(showImageLogs
            ? {
                onSnapshotCreateLogs: (chunk: string) => {
                  const trimmed = chunk.trim();
                  if (trimmed) events.log(`[image] ${trimmed}`);
                },
              }
            : {}),
        },
      );
    } finally {
      stopSpinner();
    }
    const sandboxId = sandbox.id;
    events.log(`Sandbox created: ${sandboxId}`);

    try {
      events.log("Uploading workflow source files...");
      const remoteDirs = new Set<string>();
      for (const filename of resolved.langManifest.files) {
        const remoteDir = path.posix.dirname(`${APP_DIR}/${filename}`);
        if (remoteDir !== APP_DIR) remoteDirs.add(remoteDir);
      }
      for (const dir of remoteDirs) {
        await sandbox.fs.createFolder(dir, "755");
      }
      for (const filename of resolved.langManifest.files) {
        const buf = await fs.readFile(path.join(resolved.langDir, filename));
        await sandbox.fs.uploadFile(buf, `${APP_DIR}/${filename}`);
      }

      events.log("Starting Temporal dev server...");
      await sandbox.process.createSession("temporal-server");
      const startResp = await sandbox.process.executeSessionCommand(
        "temporal-server",
        {
          command: `${TEMPORAL_BIN} server start-dev --ip 0.0.0.0 --ui-ip 0.0.0.0 --log-level warn`,
          runAsync: true,
        },
      );
      const serverCmdId = startResp.cmdId;

      events.log("Waiting for Temporal server to be healthy...");
      await this.waitForTemporal(sandbox, "temporal-server", serverCmdId, events);

      events.log("Generating signed Temporal UI preview URL...");
      const preview = await sandbox.getSignedPreviewUrl(
        TEMPORAL_UI_PORT,
        PREVIEW_URL_TTL_SECONDS,
      );
      const uiInfo: UiInfo = { sandboxId, uiUrl: preview.url };
      events.log(`Temporal UI: ${preview.url}`);
      onUiReady?.(uiInfo);

      const workflowResult = await this.startWorkerAndRunStarter(
        sandbox,
        resolved,
        events,
      );

      return { ...uiInfo, workflowResult };
    } catch (err) {
      events.log(`Launch failed: ${(err as Error).message}. Cleaning up sandbox...`);
      try {
        await sandbox.delete();
      } catch (cleanupErr) {
        events.log(`Cleanup error (ignored): ${(cleanupErr as Error).message}`);
      }
      throw err;
    }
  }

  async runEdited(
    sandboxId: string,
    patternId: string,
    language: string,
    files: Record<string, string>,
    events: SandboxEvents,
  ): Promise<string> {
    const resolved = await resolvePattern(patternId, language);
    events.log("Resolving sandbox...");
    const sandbox = await this.daytona.get(sandboxId);

    events.log("Persisting edits to disk and uploading to sandbox...");
    for (const filename of resolved.langManifest.files) {
      const incoming = files[filename];
      if (incoming === undefined) continue;
      const normalized = incoming.replace(/\r\n/g, "\n");
      await fs.writeFile(path.join(resolved.langDir, filename), normalized);
      await sandbox.fs.uploadFile(
        Buffer.from(normalized),
        `${APP_DIR}/${filename}`,
      );
    }

    return this.startWorkerAndRunStarter(sandbox, resolved, events, {
      restartWorker: true,
    });
  }

  async stop(sandboxId: string): Promise<void> {
    const sandbox = await this.daytona.get(sandboxId);
    await sandbox.delete();
  }

  private async startWorkerAndRunStarter(
    sandbox: Sandbox,
    resolved: ResolvedPattern,
    events: SandboxEvents,
    opts: { restartWorker?: boolean } = {},
  ): Promise<string> {
    const { langManifest } = resolved;

    if (opts.restartWorker) {
      events.log("Stopping previous worker...");
      await sandbox.process.executeCommand(
        `pkill -f "${langManifest.workerProcessPattern}" 2>/dev/null; true`,
      );
      try {
        await sandbox.process.deleteSession("worker");
      } catch {
        /* session may not exist yet */
      }
    }

    events.log("Starting worker...");
    await sandbox.process.createSession("worker");
    await sandbox.process.executeSessionCommand("worker", {
      command: `cd ${APP_DIR} && ${langManifest.worker}`,
      runAsync: true,
    });
    await sleep(3000);

    events.log("Triggering starter...");
    const r = await sandbox.process.executeCommand(
      `cd ${APP_DIR} && ${langManifest.starter}`,
      undefined,
      undefined,
      120,
    );
    if (r.exitCode !== 0) {
      throw new Error(`Workflow run failed: ${r.result}`);
    }
    const out = (r.result ?? "").trim();
    events.log("Workflow output:");
    for (const line of out.split("\n")) events.log(`  ${line}`);
    return out;
  }

  private async waitForTemporal(
    sandbox: Sandbox,
    sessionId: string,
    cmdId: string,
    events: SandboxEvents,
  ): Promise<void> {
    const timeoutMs = 120_000;
    await sleep(3000);
    const deadline = Date.now() + timeoutMs;
    while (Date.now() < deadline) {
      const r = await sandbox.process.executeCommand(
        `${TEMPORAL_BIN} operator cluster health 2>&1`,
        undefined,
        undefined,
        10,
      );
      if (r.exitCode === 0) return;
      await sleep(2000);
    }
    try {
      const logs = await sandbox.process.getSessionCommandLogs(sessionId, cmdId);
      const tail = (logs?.output || logs?.stderr || logs?.stdout || "").trim();
      if (tail) {
        events.log("temporal-server output:");
        for (const line of tail.split("\n").slice(-20)) events.log(`  ${line}`);
      } else {
        events.log("temporal-server produced no output (likely never started)");
      }
    } catch (e) {
      events.log(`(could not fetch server logs: ${(e as Error).message})`);
    }
    throw new Error(
      `Temporal dev server did not become healthy within ${timeoutMs / 1000}s`,
    );
  }
}
